#!/usr/bin/env bash
# This script ensures that the entire project's JavaScript source files are available
# from the `./dist` directory. This is useful for two main reasons:
# 1. Allows users to utilize the TypeScript type definitions for Lightning
# 2. Allows users to import individual ES module files from Lightning, instead of
#    using the bundled files generated by vite. This enables users to employ Tree-shaking
#    to reduce the size of their bundle.
#
# This script is required because the project's source files are currently a mix
# of JavaScript (+ manually written type definition files) and TypeScript.
# If the project is ever converted entirely to TypeScript, this script will no longer
# be necessary as `tsc` will be able to handle the entire process.

set -e # Exit with nonzero exit code if anything fails

# Make sure working directory is the root of the repository
cd "$(dirname "$0")/.."

# 1. Copy all the JavaScript source code (.js / .mjs) and
#    all the manually written type definition files (.d.ts / .d.mts)
echo "Copying all JavaScript source code to ./dist..."
find . \
  -type f \
  \( -name "*.js" -o -name "*.mjs" -o -name "*.d.mts" -o -name "*.d.ts" \) \
  -not -name "*.test.*" \
  -path "./src/*" \
  -exec sh -c 'mkdir -p ./dist/$(dirname {}) && cp {} ./dist/{}' \;

# 2. Compile all TypeScript source code (.ts / .mts) in the project
echo "Compiling all TypeScript source code to ./dist..."
tsc -P tsconfig.build.json

echo "Done!"