name: "CLA"

permissions:
  contents: read
  pull-requests: write
  actions: write
  statuses: write

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

jobs:
  CLA-Lite:
    name: "Signature"
    uses: rdkcentral/cmf-actions/.github/workflows/cla.yml@v1
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.CLA_ASSISTANT }}
