name: PR Validation

on:
  pull_request:
    branches: [ master, dev ]
  push:
    branches: [ master, dev ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x, 22.x]
        include:
          - node-version: 20.x
            experimental: false
          - node-version: 22.x
            experimental: true

    continue-on-error: ${{ matrix.experimental }}

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Type Check
      run: npx tsc --noEmit

    - name: Run tests
      run: npm test

    - name: Build
      run: npm run build

    # - name: Type Validation
      # run: npm run tsd
